import React, { useState } from 'react';
import { GeneratedReport, ReportTemplate } from '../types/reports';
import {
  ReportSummary,
  ReportFilters,
  ReportChart,
  ReportTable,
  ExportMenu,
  NBRVATReport,
} from '../components/reports';
import { formatBDT } from '../utils/formatters';
import { ArrowLeft, Calendar, User, Star, ShieldCheck, ChevronRight } from 'lucide-react';
import { generateReportFromTemplate } from '../utils/reportGenerator';

export interface ReportViewerProps {
  report: GeneratedReport;
  template?: ReportTemplate;
  onBack: () => void;
  locale?: 'en' | 'bn';
}

export const ReportViewerPage: React.FC<ReportViewerProps> = ({
  report: initialReport,
  template,
  onBack,
  locale = 'en',
}) => {
  const [currentReport, setCurrentReport] = useState<GeneratedReport>(initialReport);
  const [activeFilters, setActiveFilters] = useState<Record<string, any>>(initialReport.filters);
  const [showFilterBar, setShowFilterBar] = useState(false);

  // Re-generate report when filters change
  const handleFilterChange = (field: string, value: any) => {
    const updated = { ...activeFilters, [field]: value };
    setActiveFilters(updated);

    if (template) {
      const regenerated = generateReportFromTemplate(template, updated);
      setCurrentReport(regenerated);
    }
  };

  const handleRefresh = () => {
    if (template) {
      const regenerated = generateReportFromTemplate(template, activeFilters);
      setCurrentReport(regenerated);
    }
  };

  const isVatReport = currentReport.templateId === 'rep-nbr-vat' || currentReport.category === 'compliance';

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12">
      {/* Navigation Top Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <button
          onClick={onBack}
          className="inline-flex items-center gap-2 text-xs font-bold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>{locale === 'bn' ? 'রিপোর্ট লাইব্রেরিতে ফিরুন' : 'Back to Reports Library'}</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowFilterBar(!showFilterBar)}
            className="py-2 px-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700/60 transition-colors"
          >
            {showFilterBar ? 'Hide Filters' : 'Edit Filters'}
          </button>
          <ExportMenu report={currentReport} onRefresh={handleRefresh} locale={locale} />
        </div>
      </div>

      {/* Header Info Banner */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[11px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
                {currentReport.category}
              </span>
              <span className="text-xs text-slate-400 font-mono">
                ID: {currentReport.id}
              </span>
            </div>

            <h2 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white mt-1.5">
              {locale === 'bn' && currentReport.templateNameBangla
                ? currentReport.templateNameBangla
                : currentReport.templateName}
            </h2>

            {currentReport.description && (
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-2xl leading-relaxed">
                {currentReport.description}
              </p>
            )}
          </div>

          <div className="text-xs font-mono text-slate-500 dark:text-slate-400 flex flex-col md:items-end gap-1">
            <div className="flex items-center gap-1.5">
              <Calendar className="w-3.5 h-3.5 text-slate-400" />
              <span>
                Period: <strong className="text-slate-800 dark:text-slate-200">{currentReport.dateRange.start}</strong> to{' '}
                <strong className="text-slate-800 dark:text-slate-200">{currentReport.dateRange.end}</strong>
              </span>
            </div>
            <div className="flex items-center gap-1.5">
              <User className="w-3.5 h-3.5 text-slate-400" />
              <span>Generated by: {currentReport.generatedByName}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Collapsible Filter Bar */}
      {showFilterBar && template && (
        <ReportFilters
          filters={template.defaultFilters}
          activeFilters={activeFilters}
          onFilterChange={handleFilterChange}
          locale={locale}
        />
      )}

      {/* If NBR VAT Report, render official compliance view */}
      {isVatReport ? (
        <NBRVATReport report={currentReport} onRefresh={handleRefresh} locale={locale} />
      ) : (
        <>
          {/* Executive Summary Cards */}
          <ReportSummary summary={currentReport.summary} locale={locale} />

          {/* Visual Charts Grid */}
          {currentReport.charts && currentReport.charts.length > 0 && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {currentReport.charts.map((chart) => (
                <ReportChart
                  key={chart.id}
                  chart={chart}
                  data={currentReport.data}
                  locale={locale}
                />
              ))}
            </div>
          )}

          {/* Detailed Data Table */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Detailed Records ({currentReport.data.length} Total)
              </h3>
            </div>

            <ReportTable
              columns={currentReport.columns}
              data={currentReport.data}
              locale={locale}
            />
          </div>

          {/* Technician Workforce Summary (if present) */}
          {currentReport.technicianBreakdown && currentReport.technicianBreakdown.length > 0 && (
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                    Field Technician Workforce Performance
                  </h4>
                  <p className="text-xs text-slate-500">
                    Breakdown of job allocations, completions, and CSAT scores across Dhaka and regional hubs.
                  </p>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-xs text-left">
                  <thead>
                    <tr className="bg-slate-50 dark:bg-slate-800/60 border-b border-slate-200 dark:border-slate-800 text-[11px] font-bold text-slate-500 uppercase">
                      <th className="py-2.5 px-4">Technician</th>
                      <th className="py-2.5 px-4 text-center">Assigned Jobs</th>
                      <th className="py-2.5 px-4 text-center">Completed</th>
                      <th className="py-2.5 px-4 text-right">Revenue (BDT)</th>
                      <th className="py-2.5 px-4 text-center">Avg Rating</th>
                      <th className="py-2.5 px-4 text-right">SLA Compliance</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                    {currentReport.technicianBreakdown.map((t, idx) => (
                      <tr key={idx} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/30">
                        <td className="py-3 px-4 font-semibold text-slate-900 dark:text-white">
                          {t.name}
                        </td>
                        <td className="py-3 px-4 text-center font-mono">{t.jobs}</td>
                        <td className="py-3 px-4 text-center font-mono text-emerald-600 font-semibold">
                          {t.completed}
                        </td>
                        <td className="py-3 px-4 text-right font-mono font-bold text-slate-900 dark:text-white">
                          {formatBDT(t.revenue, locale)}
                        </td>
                        <td className="py-3 px-4 text-center">
                          <span className="inline-flex items-center gap-1 font-semibold text-amber-500">
                            <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-500" />
                            {t.rating.toFixed(1)}
                          </span>
                        </td>
                        <td className="py-3 px-4 text-right font-mono font-bold text-emerald-600 dark:text-emerald-400">
                          {t.slaPercent}%
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};
