import * as XLSX from 'xlsx';
import { GeneratedReport } from '../types/reports';

/**
 * FieldOps Pro - Excel & CSV Export Generator
 * Formats report summaries, transaction ledgers, VAT calculations, and technician metrics
 * into formatted Microsoft Excel (.xlsx) workbooks and CSV files.
 */

export function exportReportToExcel(report: GeneratedReport): void {
  const wb = XLSX.utils.book_new();

  // SHEET 1: Summary Sheet
  const summaryRows: any[] = [
    ['FIELDOPS PRO - ENTERPRISE FIELD SERVICE MANAGEMENT BANGLADESH'],
    ['Report Name:', report.templateName],
    ['Report ID:', report.id],
    ['Period:', `${report.dateRange.start} to ${report.dateRange.end}`],
    ['Generated At:', new Date(report.generatedAt).toLocaleString()],
    ['Generated By:', report.generatedByName || 'System Lead'],
    ['NBR BIN:', '002938102-0101'],
    [],
    ['KEY PERFORMANCE INDICATORS (KPIs)'],
    ['Metric', 'Value'],
  ];

  if (report.summary?.metrics) {
    report.summary.metrics.forEach((m) => {
      let val = m.value;
      if (m.format === 'currency' && typeof m.value === 'number') {
        val = `৳ ${m.value.toLocaleString()}`;
      }
      summaryRows.push([m.label, val]);
    });
  }

  // If VAT summary exists
  if (report.vatSummary) {
    summaryRows.push([]);
    summaryRows.push(['NATIONAL BOARD OF REVENUE (NBR) VAT MUSHAK 6.3 BREAKDOWN']);
    summaryRows.push(['Head', 'Amount in BDT']);
    summaryRows.push(['Total Taxable Sales (A)', report.vatSummary.totalTaxableSales]);
    summaryRows.push(['Standard VAT Rate', '15%']);
    summaryRows.push(['Output VAT Collected (B = A x 15%)', report.vatSummary.outputVAT]);
    summaryRows.push(['Input VAT Credit (C)', report.vatSummary.inputVATCredit]);
    summaryRows.push(['Net VAT Payable to Govt (B - C)', report.vatSummary.netVATPayable]);
  }

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary & KPIs');

  // SHEET 2: Detailed Data Ledger
  if (report.data && report.data.length > 0 && report.columns) {
    const headers = report.columns.map((c) => c.header);
    const dataRows = report.data.map((row) => {
      return report.columns.map((c) => {
        const val = row[c.field];
        if (val === null || val === undefined) return '';
        return val;
      });
    });

    const tableSheetData = [headers, ...dataRows];
    const wsData = XLSX.utils.aoa_to_sheet(tableSheetData);
    XLSX.utils.book_append_sheet(wb, wsData, 'Operational Ledger');
  }

  // SHEET 3: Technician Workforce Breakdown (if applicable)
  if (report.technicianBreakdown && report.technicianBreakdown.length > 0) {
    const techHeaders = ['Technician', 'Assigned Jobs', 'Completed Jobs', 'Revenue (BDT)', 'Rating', 'SLA %'];
    const techData = report.technicianBreakdown.map((t) => [
      t.name,
      t.jobs,
      t.completed,
      t.revenue,
      t.rating,
      `${t.slaPercent}%`,
    ]);

    const wsTech = XLSX.utils.aoa_to_sheet([techHeaders, ...techData]);
    XLSX.utils.book_append_sheet(wb, wsTech, 'Technician Performance');
  }

  // Generate filename
  const cleanName = report.templateName.replace(/[^a-zA-Z0-9]/g, '_');
  const fileName = `${cleanName}_${report.dateRange.start}_to_${report.dateRange.end}.xlsx`;

  // Write and trigger download
  XLSX.writeFile(wb, fileName);
}

/**
 * Exports detailed report data directly to CSV format
 */
export function exportReportToCSV(report: GeneratedReport): void {
  if (!report.data || report.data.length === 0 || !report.columns) {
    return;
  }

  const headers = report.columns.map((c) => c.header);
  const rows = report.data.map((row) => {
    return report.columns.map((c) => {
      let val = row[c.field];
      if (val === null || val === undefined) return '';
      // Escape quotes
      const strVal = String(val).replace(/"/g, '""');
      return `"${strVal}"`;
    }).join(',');
  });

  const csvContent = [headers.map((h) => `"${h}"`).join(','), ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const cleanName = report.templateName.replace(/[^a-zA-Z0-9]/g, '_');
  link.download = `${cleanName}_${report.dateRange.start}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
